name: Release Request
run-name: Release Request

on:
  pull_request:
    types:
      - closed
      - edited
      - opened
    branches:
      - master

jobs:
  publish_release_request:
    name: ${{ github.event.action == 'closed' && 'Publish ' || 'Verify ' }}Release Request
    permissions:
      contents: write
    uses: Arthri/release_request/.github/workflows/release_request.yml@v1
